# ##handlers/constants.py
# Базовые состояния
PHONE = "PHONE"
FULL_NAME = "FULL_NAME"
LOCATION = "LOCATION"
MAIN_MENU = "MAIN_MENU"
ORDER_ACTION = "ORDER_ACTION"
ORDER_CONFIRMATION = "ORDER_CONFIRMATION"
SELECT_MONTH_RANGE = "SELECT_MONTH_RANGE"
BROADCAST_MESSAGE = "BROADCAST_MESSAGE"
AWAIT_MESSAGE_TEXT = "AWAIT_MESSAGE_TEXT"
ADMIN_MESSAGE = "ADMIN_MESSAGE"
AWAIT_USER_SELECTION = "AWAIT_USER_SELECTION"
SELECT_MONTH_RANGE_STATS = "SELECT_MONTH_RANGE_STATS"

# Состояния для управления конфигурацией
CONFIG_MENU = "CONFIG_MENU"
ADD_ADMIN = "ADD_ADMIN"
ADD_PROVIDER = "ADD_PROVIDER"
ADD_ACCOUNTANT = "ADD_ACCOUNTANT"
ADD_STAFF = "ADD_STAFF"
ADD_HOLIDAY_DATE = "ADD_HOLIDAY_DATE"
ADD_HOLIDAY_NAME = "ADD_HOLIDAY_NAME"

# Состояния для редактирования меню
EDIT_MENU_DAY = "EDIT_MENU_DAY"
EDIT_MENU_FIRST = "EDIT_MENU_FIRST"
EDIT_MENU_MAIN = "EDIT_MENU_MAIN"
EDIT_MENU_SALAD = "EDIT_MENU_SALAD"