version: '3.8'

services:
  bot:
    build: .
    container_name: lunch_bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data  # Для сохранения БД при перезапусках
    environment:
      - TZ=Europe/Moscow  # Ваша временная зона
