# constants.py
PHONE = "PHONE"
FULL_NAME = "FULL_NAME"
LOCATION = "LOCATION"
MAIN_MENU = "MAIN_MENU"
ORDER_ACTION = "ORDER_ACTION"
ORDER_CONFIRMATION = "ORDER_CONFIRMATION"
SELECT_MONTH_RANGE = "SELECT_MONTH_RANGE"
BROADCAST_MESSAGE = "BROADCAST_MESSAGE"
AWAIT_MESSAGE_TEXT = "AWAIT_MESSAGE_TEXT"
ADMIN_MESSAGE = "ADMIN_MESSAGE"
AWAIT_USER_SELECTION = "AWAIT_USER_SELECTION"
SELECT_MONTH_RANGE_STATS = "SELECT_MONTH_RANGE_STATS"


from .constants import (
    AWAIT_MESSAGE_TEXT,
    PHONE, FULL_NAME, 
    LOCATION, MAIN_MENU, 
    ORDER_ACTION, 
    ORDER_CONFIRMATION, 
    SELECT_MONTH_RANGE,
    BROADCAST_MESSAGE, 
    ADMIN_MESSAGE, 
    AWAIT_USER_SELECTION, 
    SELECT_MONTH_RANGE_STATS
)